package com.bootcampCognizantJavaDeveloper.estruturaDeDados.arvores;

public class Anotacoes {
	
	//CONCEITO
	//ESTRUTURA DE DADOS BIDIMENSIONAL
	//NÃO LINEAR
	//CONSTITUÍDA DE NÓS QUE REPRESENTAM UM MODELO HIERÁRQUICO
	//ARMAZENAM OD DADOS COM BASE EM RELAÇÕES DE DEPENDÊNCIAS.
	//LISTAS, FILAS E PILHAS SÃO ESTRUTURA LINEARES
	
	//UTILIZAÇÃO
	//SISTEMAS DE ARQUIVOS
	//BANCO DE DADOS
	//INTERFACES GRÁFICAS
	//PÁGINAS WEB

	//CARACTERÍSTICAS DE UMA ÁRVORE HIERÁRQUICA
	//NÓ
	//RAIZ
	//PAI E FILHO
	//IRMAO
	//NIVEL DE UM NÓ(POSIÇÃO HIERÁRQUICA COM RELAÇÃO A RAIZ)
	//ALTURA OU PROFUNDIDADE(GRAU MÁXIMO DOS NÓS)
	//FOLHA OU NÓ TERMINAL
	//NÓ INTERNO
	//GRAU DE UM NÓ
	//SUBÁRVORES
	
	//TIPOS DE ÁRVORES
	//ÁRVORE BINÁRIA
	//ÁRVORE AVL
	//ÁRVORE ORDENADA
	//ÁRVORE RUBRO-NEGRA
	//ÁRVORE 2-3
	//ÁRVORE 2-4
	//ÁRVORE B
	//ÁRVORE B+
	//ÁRVORE HIPERBÓLICA
	
	
}
