package com.bootcampCognizantJavaDeveloper.EntendendoMetodosJava;

public class AnotacoesRetorno {
	
	//RELEMBRANDO
	//É UMA INSTRUÇÃO DE INTERRUPÇÃO
	//SIMBOLOGIA: RETURN
	
	//FUNCIONAMENTO
	//O MÉTODO EXECUTA SEU RETORNO QUANDO:
	//COMPLETA TODAS SUAS INSTRUÇÕES INTERNAS
	//CHEA A UMA DECLARAÇÃO EXPLICITA DE RETORNO
	//LANCA UMA EXCEÇÃO
	
	//CONSIDERAÇÕES
	//O TIPO DE RETORNO DO MÉTODO É DEFINIDO NA SUA CRIAÇÃO E PODE SER UM TIPO PRIMITIVO OU OBJETO
	//O TIPO DE DADO DO RETURN, DEVE SER COMPÁTIVEL COM O DO MÉTODO
	//SE O MÉTODO FOR SEM RETORNO(VOID), PODE OU NÃO TEM UM 'RETURN' PARA ENCERRAR SUA EXECUÇÃO

}
