package com.bootcampCognizantJavaDeveloper.logicaCondicionalControleFluxo;

public class AnotacoesOperadoresRelacionais {
	
	//CONCEITUAÇÃO OPERADORES RELACIONAIS
	//SÃO SIMBOLOS ESPECIAIS QUAIS SAO CAPAZES DE REALIZAR COMPARAÇÕES
	//ENTRE DETERMINADOS OPERANDOS E EM SEGUIDA RETORNA UM RESULTADO
	
	//TIPOS:
	//SIMILARIDADE: IGUAL, DIFERENTE
	//TAMANHO: MAIOR, MAIOR IGUAL, MENOR, MENOR IGUAL
	
	//UTILIZAÇÃO
	//SIMILARIDADE
	//IGUALDADE: DETERMINA SE UM OPERANDO É IGUAL AO OUTRO
	//DIFERENÇA: DETERMINA SE UM OPERANDO NÃO É IGUAL AO OUTRO		
	//IGUALDADE: ==
	//DIFERENÇA: !=
	
	//TAMANHO
	//MAIOR: DETERMINA SE UM OPERANDO É MAIOR DO QUE O OUTRO
	//MAIOR IGUAL: DETERMINA SE UM OPERANDO É MAIOR OU IGUAL A OUTRO
	//MENOR: DETERMINA SE UM OPERANDO É MENOR DO QUE O OUTRO
	//MENOR IGUAL: DETERMINA SE UM OPERANDO É MENOR OU IGUAL A OUTRO
	//MAIOR: >
	//MAIOR IGUAL >=
	//MENOR: <
	//MENOR IGUAL: <=
	

}
