package com.bootcampCognizantJavaDeveloper.logicaCondicionalControleFluxo;

public class AnotacoesControleDeFluxo {
	
	//CONCEITO
	//SÃO ESTRUTURAS QUE TEM A CAPACIDADE DE DIRECIONAR O FLUXO DE EXECUÇÃO DO CÓDIGO
	
	//TIPOS IF, IF-ELSE, IF-ELSE-IF, SWITCH E O OPERADOR TERNÁRIO
	//REPETIÇÃO: FOR, WHILE, DO WHILE
	//INTERRUPÇÃO: BREAK, CONTINUE E RETURN
	
	//CRIAÇÃO: ESTRUTURA QUE AVALIA UMA CONDIÇÃO BOOLEANA OU VARIÁVEL PARA DIRECIONAR O FLUXO DE EXECUÇÃO
	//OPÇÕES: IF(SE), SWITCH(ESCOLHA) E OPERADOR TERNÁRIO
	
	//OBS: OPERADOR TERNÁRIO DEVE SER EVITÁDO AO MÁXIMO
	
	//BOAS PRÁTICAS
	//***SWITCH É PARA VALORES EXATOS E IF PARA EXPRESSÕES BOOLEANAS
	//EVITAR USAR O DEFAULT DO SWITCH PARA "CASOS GENÉRICOS"
	//EVITAR O EFEITO "FLECHA" DOS IF´S
	//EVITAR MUITOS IF´S ANINHADOS
	//USAR A BOA PRÁTICA DA AULA 2(CRIAR VARIÁVEIS INTERMEDIÁRIAS) PARA DIMINUIR O IF

}
