package com.bootcampCognizantJavaDeveloper.collections;

public class Anotacoes {

	//COLLECTION
	//É UM OBJETO QUE AGRUPA MÚLTIPLOS ELEMENTOS(VARIÁVEIS PRIMITIVAS OU OBJETOS)
	//DENTRO DE UMA ÚNICA UNIDADE
	//SERVE PARA ARMAZENAR E PROCESSAR CONJUNTOS DE DADOS DE FORMA EFICIENTE
	
	//COMPOSIÇÃO
	//COLLECTION É ESTRUTURA POR INTERFACES
	
	//INTERFACES: É UM CONTRATO QUE QUANDO ASSUMIDO POR UMA CLASSE DEVE SER IMPLEMENTADO.
	
	//LIST
	//ELEMENTOS DUPLICADOS E GARANTE ORDEM DE INSERÇÃO
	
	//**ARRAYLIST DEVE SER USADO ONDE MAIS OPERAÇÃOES DE PESQUISAS SÃO NECESSÁRIAS
	//**LINKEDLIST DEVE SER USADO ONDE MAIS OPERAÇÕES DE INSERÇÃO E EXCLUSÃO SÃO NECESSÁRIAS
	
	//SET
	//NÃO PERMITE ELEMENTOS DUPLICADOS
	//NÃO POSSUI ÍNDICE
	//NÃO GARANTE ORDEM DE INSERÇÃO(BAGUNÇADO)
	
	//MAP
	//ELEMENTOS ÚNICOS(KEY) PARA CADA VALOR(VALUE)
	
	//REFERENCE METHOD
	//METHOD REFERENCE É UM NOVO RECURSO DO JAVA 8 QUE QUE PERMITE FAZER REFERÊNCIA A UM MÉTODO OU CONSTRUTOR
	//DE UMA CLASSE( DE FORMA FUNCIONAL) E ASSIM INDICAR QUE ELE DEVE SER UTILIZADO NUM PONTO ESPECÍFICO
	//DO CÓDIGO, DEIXANDO-O O MAIS SIMPLES E LEGÍVEL. PARA UTILIZA-LO, BASTA INFORMAR UMA CLASSE
	//OU REFERÊNCIA SEGUIDA DO SÍMBOLO "::" E O NOME DO MÉTODO SEM OS PARÊNTESES NO FINAL
	//(SERVE PARA SIMPLIFICAR UMA LAMDBA EXPRESSION)
	
	//STREAM API
	//A STREAMS API TRAZ UMA NOVA OPÇÃO PARA A MANIPULAÇÃO DE COLEÇÕES EM JAVA SEGUINDO OS PRINCÍPIOS DA PROGRAMAÇÃO
	//FUNCIONAL. COMBINADA COM AS EXPRESSÕES LAMBDA, ELA PROPORCIONA UMA FORMA DIFERENTE DE LIDAR COM CONJUNTOS DE ELEMENTOS
	//OFERECENDO AO DESENVOLVEDOR UMA MANEIRA SIMPLES E CONCISA DE ESCREVER CÓDIGO QUE RESULTA EM FACILIDADE DE MANUTENÇÃO
	//E PARALELIZAÇÃO SEM EFEITOS INDEDEJADOS EM TEMPO DE EXECUÇÃO
	
	
	
}
