package com.bootcampCognizantJavaDeveloper.streamApi;

public class AnotacoesStreamAPI {
	
	//CLASSE ANÔNIMA
	//A CLASSE ANÔNIMA EM JAVA É UMA CLASSE QUE NÃO RECEBEU UM NOME
	//E É TANTO DECLARADO E INSTANCIADO EM UMA ÚNICA INSTRUÇÃO.
	//VOCÊ DEVE CONSIDERAR O USO DE UMA CLASSE ANÔNIMA SEMPRE QUE VOCÊ PRECISA
	//PARA CRIAR UMA CLASSE QUE SERÁ INSTÂNCIADO APENAS UMA VEZ
	
	
	//FUNCTIONAL INTERFACE
	//QUALQUER INTERFACE COM UM SAM(SINGLE ABSTRACT METHOD) É UMA INTERFACE FUNCIONAL E SUA IMPLEMENTAÇÃO
	//PODE SER TRATADA COMO EXPRESSÕES LAMBDA
	
	//INTERFACES PARA ESRTUDAR
	//COMPARATOR
	//CONSUMER
	//FUNCTION
	//PREDICATE
	
	//LAMBDAS
	//UMA FUNÇÃO LAMBDA, É UMA FUNCÃO SEM DECLARAÇÃO, ISTO É, NÃO É NECESSÁRIO COLOCAR NOME, UM TIPO DE 
	//RETORNO E O MODIFICADOR DE ACESSO. A IDEIA É QUE  O MÉTODO SEJA DECLARADO NO MESMO LUGAR EM QUE SERÁ USADO
	//AS FUNÇÕES LAMBDA EM JAVA TEM A SINTAXE DEFINIDA COMO (ARGUMENTO) -> (CORPO)
	
	
	
	
	
	

}
